### ISSUE TITLE
Problem avec wander

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#25]
En ce moment les people font un simple wander mais le mouvement n'est pas realiste car ils restent bloqués à certains endroits ou tournent en boucle sur une portion.

A mon avis une des facons de régler ca est de leur faire un goto vers une destination random et de reinitiailiser cette destination uen fois arrivé.

**Comment by agrignard** [comment]
Le problem ici est que le goto est beaucoup plus gourmand en temps de simulation

**Comment by agrignard** [comment]
trigger ```` people wandering ```` to see how the goto is greedy

**Comment by ptaillandier** [comment]
le problème est qu'aucun des graphes n'a de composante connexe unique : il y a des trous partout et du coup le goto passe son temps à recalculer des plus court chemin n'existent pas. La meilleure solution est de proposer des shapefiles propres où toutes les polylignes sont connectées entre elles.

**Comment by agrignard** [comment]
Je me rends pas bien compte de la complexité de la reconnexion, si ce n'est pas trop compliqué a reconnecter. Les datas sont celle de Opendata on de openstreetmap après pour les sites d'interventions on a tout refait à la main donc ca devrait etre connecté
