### ISSUE TITLE
Grso bouchons sur les champs

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#27]
Au bout de quelques pas de simu toute les voitures se retrouvent bloquées sur les champs. Lorsque que ne developpe le modèle que queles minutes on ne s'en rend pas compte mais quand on le laisse tourner oui

Pour reproduire cela rapidement il suffit de changer le step de la simu est de le mettre à 
````
float step <- 10 #sec; 
`````
et du coup il n'y a quasi plus de voiture ailleurs.

**Comment by ptaillandier** [comment]
non, pas lanes = 0 c'est le nug assuré (c'est pas prévu :p ).
Trois solutions :
 - on met des poids énormes aux routes n'existant plus (les agents qui sont
déjà dessus font finir leur chemin, mais les autres ne les utiliseront pas)
 - on reconstruit tout le graphe (attention avec les agents déjà
enregistrés sur les routes)
 - on met à jour que les parties du graphe qui ont été modifiée : nécessite
de faire un peu attention.

Le jeu. 16 janv. 2020 à 13:27, Tri Nguyen-Huu <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
oups j'ai mis pro_lanes à zero pour le grand palais et la concorde... pour le moment ce n'est pas utiliser donc pas de bug mais ca peut permettre d'identifier les routes a fermer pour le moment

Pour les champs en revanche c'est passé de 4 à 2 ca ca devrait marcher

**Comment by ptaillandier** [comment]
c'est pas grave, on peut très bien utiliser cette info pour savoir quelles
routes interdire.

Le jeu. 16 janv. 2020 à 13:51, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by tnguyenh** [comment]
J'aime pas la solution de mettre des gros poids, je trouve ça pas propre ;)
Par contre ça peut pas marcher si tu mets step <- 10#s, si je dis pas de conneries la durée des feux est comptée en nombre de cycles (c'est bien ça Patrick), donc du coup tu as des feux rouges interminables. D'où bouchons (du coup avec les paramètres actuels, 16mn).

**Comment by ptaillandier** [comment]
J'aime pas la solution de mettre des gros poids, je trouve ça pas propre ;)
En fait, moi j'aime bien. C'est pas si moche, c'est simple, c'est sur qu'on
va pas avoir de bugs :p .

Par contre ça peut pas marcher si tu mets step <- 10#s, si je dis pas de
conneries la durée des feux est comptée en nombre de cycles (c'est bien ça
Patrick), donc du coup tu as des feux rouges interminables. D'où bouchons
(du coup avec les paramètres actuels, 16mn).
Pour les feux, on fait comme on veut : le codage du passage du vert au
rouge est ultra simple. Cela peut être en nombre de cycle ou en temps,
c'est à nous de choisir



Le jeu. 16 janv. 2020 à 15:36, Tri Nguyen-Huu <notifications@github.com> a
écrit :
