### ISSUE TITLE
Image of the simulation

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#30]
We need to converge for a code color ASAP and map it on the 3D rendering

Here is a potential proposal (I am not the designer in the group, it would need to be validate by a real designer /Architect...)

<img width="1438" alt="Screen Shot 2020-01-16 at 11 58 01" src="https://user-images.githubusercontent.com/3928502/72545767-90bf7c80-3857-11ea-9ba4-95b1f34c4b12.png">

**Comment by agrignard** [comment]
<img width="1445" alt="Screen Shot 2020-01-16 at 12 01 23" src="https://user-images.githubusercontent.com/3928502/72546021-04fa2000-3858-11ea-9f60-191f100e0787.png">

**Comment by tnguyenh** [comment]
Ca ressemble à du bon blueprint d'archi. On dirait une image en négatif.

 Tu nous mets une version sur fond blanc pour voir ?

**Comment by tnguyenh** [comment]
<img width="1438" alt="72545767-90bf7c80-3857-11ea-9ba4-95b1f34c4b12" src="https://user-images.githubusercontent.com/18676913/72546118-7e126b00-388a-11ea-8de9-cc1fd478434a.png">

En mode négatif...

**Comment by agrignard** [comment]
pas mal!!!

**Comment by agrignard** [comment]
juste avec white background pas top
<img width="1346" alt="Screen Shot 2020-01-16 at 12 03 22" src="https://user-images.githubusercontent.com/3928502/72546193-54d8e700-3858-11ea-9e0d-fccab3590a1c.png">

**Comment by tnguyenh** [comment]
nan pas top. Après ça fait dessin au crayon...

**Comment by agrignard** [comment]
on bosse sur un version photoshop

**Comment by agrignard** [comment]
![DataMIT_3](https://user-images.githubusercontent.com/3928502/72640970-00f0ff80-3937-11ea-84c6-62a571008560.jpg)
