### ISSUE TITLE
Make lanes consistent between shapefile and project file

### ISSUE THREAD

**Issue by tnguyenh** [agrignard/ReChamp#32]
The lanes position are not well placed in the model. It is mostly due to the fact that the location of lanes is not consistent between the shapefile, the PCA document and the model.

Actually it cannot work at the moment since the number of lanes is not the same in the shapefile and in PCA document.

**Comment by agrignard** [comment]
What do you mean not well placed in the model? The one that appears when pressing M? or the agent? How can I help here?

**Comment by tnguyenh** [comment]
I mean lane positions are not consistent between the ones we have in reality, the ones generated by the model from the shapefile, and PCA document.

**Comment by agrignard** [comment]
I close it now for a more specific one (i don't thnik we will be able to have something totally coherent between the project and the real shape file)  what matters now is to have something coherent in the simualtion even if it's not exactly the pca project

@tnguyenh i let you reopen this issue if you think it makes sens
