### ISSUE TITLE
update trajectory and the offset display for Pedestrian

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#34]
Les trajectoire sont calculées sur la location mais pas avec l'offset

**Comment by agrignard** [comment]
C'est ok pour les voitures masi pas pour les peitosn ni pour les bikes , j'imagine que c'est la même technique il ya peut etre du code a refactoriser ou a mettre dans une action global ou une espece parent?

**Comment by tnguyenh** [comment]
ouais je m'en occupe.

**Comment by tnguyenh** [comment]
Ouais y'a un calcul de location qui est pas cohérent du tout avec le calcul de fuzyness. 
Les piétons on l'air d'aller pas mal en ligne droite sans prendre tout le trottoir, j'arrange ça au passage ? Et je les smooth un peu pour éviter la téléportation ?

**Comment by agrignard** [comment]
pour le moment il se ballade sur le road osm il me semble avec du gros offset et en effet la trajectoire n'est pas tu totu la bonne, donc why not faire la meme chose que pour les bagnolles, encore une fois a condition de garder du framerate et de pas trop dupliquer de code non plus.

**Comment by tnguyenh** [comment]
la duplication de code c'est un peu obligatoire car y'a des petites variations, une voiture ne se comporte pas comme un piéton. Le framerate ça changera pas grand chose, le code est linéaire, et c'est les fonctions d'affichage qui le kill, et ça ne rajoute rien en terme de fonction d'affichage.

**Comment by agrignard** [comment]
On a toujours ça faire pour les pietons

**Comment by tnguyenh** [comment]
J'ai pas encore checké les piétons, je fais ça demain.

**Comment by agrignard** [comment]
ok c'est bien nimp pour le moment

**Comment by agrignard** [comment]
@tnguyenh tu jettes un coup d'oeil?
