### ISSUE TITLE
Crash sometime

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#35]
En changeant d'etat (en appuyant sur espace maintenant) la simu parfois s'arrete... j'ai l'impression que ca monte beaucoup en memoire (peut etre a cause de l'ajout des trajectoire)

**Comment by agrignard** [comment]
Ca foire bien dans l'etat actuel mais difficile à reproduire et la simu s'arrete juste tranquillou , on va dire que c'est le bug de fin de semaine...

**Comment by agrignard** [comment]
Assez facile a reproduire dès que la la simu a dépassé les 100 cycles, il doti y avoir un truc en mémoire qui bouffe tout...

**Comment by agrignard** [comment]
Cool , ca sentait la petite ligne maléfique dans l'updateSimu

**Comment by tnguyenh** [comment]
C'est peut-être mon ordi, mais moi espace ça crash la simu régulièrement. Sauf que quand j'appuie sur espace, la simu est recentrée (ce qui est pénible d'ailleurs). Y'a pas un conflit d'utilisation avec la touche espace ?

**Comment by agrignard** [comment]
y'a un problem avec la touche espace en effet mais c'est un bug GAMA (ok on est sur z maintenant) 

Est ce que ca crash tjs chez toi? Moi c'est ok

**Comment by ptaillandier** [comment]
Chez moi (avec la touche z), cela n'a jamais planté.

**Comment by agrignard** [comment]
ca à l'air de bien marché
