### ISSUE TITLE
Problem with car trajectory

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#43]
It seems that sometime (maybe when a car is relocated) the trajectory display is weird, it makes long line along the simualtion  (easier to see with a white background (press "space)) but we can see t also with the black background and by decreasing the transparency

**Comment by tnguyenh** [comment]
yes, I'll correct that. Is it normal that the slider transparency does nothing ?

**Comment by agrignard** [comment]
just fix the transparency (it was indeed not used)

**Comment by agrignard** [comment]
it still
![Uploading Screen Shot 2020-01-20 at 22.46.50.png…]()
 here (especially when switching state)

**Comment by tnguyenh** [comment]
Strange... Are you sure to have the last version ? It's working for me, and I've commited all the changes...

**Comment by tnguyenh** [comment]
I committed again the file with an added blank line in order to see if you get it.

**Comment by tnguyenh** [comment]
It might also fix a bit of the strange trajectories.

**Comment by agrignard** [comment]
Ok I don't have it anymore
