### ISSUE TITLE
Gros bouchon

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#45]
Dans certains cas des gros bouchons se forment, je pense qu'il  audra penser à avoir une sorte de fonction purge appeleé toute les heure  pour eviter que ca se produise au bout de 2-3h de simu

Je mets queqlues imprim ecran des que ca arrive si ca peut aider à identifier la cause.
<img width="396" alt="Screen Shot 2020-01-20 at 12 38 52" src="https://user-images.githubusercontent.com/3928502/72747371-6e44a080-3b82-11ea-8341-172251b1d350.png">

**Comment by ptaillandier** [comment]
Soit on fait un reset de la sim, soit on désactive les feux pendant un
certains nombre de cycles (cela devrait marcher aussi)

Le lun. 20 janv. 2020 à 18:43, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by tnguyenh** [comment]
Y'a pas beaucoup de ponts utilisables d'ailleurs, en config futur ça force énormément de voitures sur la Concorde.

**Comment by agrignard** [comment]
voiture bloquées sur la place de l'etoile
<img width="1920" alt="Screen Shot 2020-01-20 at 22 43 15" src="https://user-images.githubusercontent.com/3928502/72773867-8e9e4a80-3bd6-11ea-9e81-3c1dd0dcc3f1.png">

**Comment by agrignard** [comment]
in state 0 some car are still taking the new road a la concorde 
<img width="560" alt="Screen Shot 2020-01-20 at 22 50 41" src="https://user-images.githubusercontent.com/3928502/72774092-5f3c0d80-3bd7-11ea-82e2-8238e180bb2e.png">

**Comment by tnguyenh** [comment]
Yes it's normal I didn't change the new road in order to make it work yesterday, I was busy debugging.

**Comment by agrignard** [comment]
A rechcker plus specifiquement avec les nouvelles modifs de Tri
