### ISSUE TITLE
concurrent modification when switching between scenarios

### ISSUE THREAD

**Issue by tnguyenh** [agrignard/ReChamp#46]
Just to remember to fix this at one point. When switching a lot and fast between scenarios, I get the following exception.

![image](https://user-images.githubusercontent.com/18676913/72751744-ba163a80-3bc0-11ea-965a-8c6691c1e1ba.png)

I don't know if there is a clean way to prevent that, anyway we can still use flags in order to avoid switching to fast or display agents when stuff are being recalculated.

**Comment by agrignard** [comment]
I don't see it anymore so i close this issue so far
