### ISSUE TITLE
FRAMERATE LOST

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#47]
WARNING HERE: I test on real condition and with all the recen tchange the framerate is clearly not there anymore... I think there is maybe too much computation regarding trajectories, drving skills etc etc...
I will investigate but it's not as smooth as it used to be which is now the TOP priority

**Comment by tnguyenh** [comment]
What changes did you do for the real conditions ? Computation is not supposed to be heavy in that model, since most of it is linear. This is the visualisation that kills the framerate. Drawing long lines behind agents is something that really hurts the framerate for example.

**Comment by agrignard** [comment]
yes maybe it's the trajectory, I have to check all of this

**Comment by tnguyenh** [comment]
That's not the trajectories. I'm gonna investigate this a little bit, but there might be an issue with pedestrian, or bikes (or buses). 

I know it is possible to improve a little bit optimizing the code for cars.

**Comment by ptaillandier** [comment]
j'ai quand même l'impression que les trajectoires (en tout cas leur
affichage) jouent pas mal : quand je mets à false dans le panneau des
paramètres tout ce qui concerne l'affichage des trajectoires, cela divise
presque par 2 la durée d'un cycle.

Le mer. 22 janv. 2020 à 12:58, Tri Nguyen-Huu <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
pour le strajectoroires j'affice en ce moment entre 25 et 50 points ar agents donc oui ca peut etre lourd. Mais j'avais l'impression (peut etre jsute une impression) que j'avsi un bon framerate à un moment donné meme avec les trajectoires.

Bon à voir ce que je peux faire (peut etre pas afficher les trajectories pour tout le monde, genre que les bagnoles si on veu montrer que le traffic) aussi en ayant un step plus plus haut je peux afficher moins de point pour le meme resulta visuel.

**Comment by agrignard** [comment]
Pas vraiment un bug finalement
