### ISSUE TITLE
potential memory leak....

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#50]
Ce qui devait arriver arriva...

j ai l impression qu il y a un jolie petit memory leak qui prend bien du temps a apparaitre... 

voila ce que jai au bout de 30000 iterations....
![Screen Shot 2020-01-23 at 8 07 48 PM](https://user-images.githubusercontent.com/3928502/73037291-7881cb80-3e1c-11ea-8a5b-0275c16126ab.png)

**Comment by ptaillandier** [comment]
A tester : pour les graphes, mettre use_cache à false:
people_graph <- people_graph use_cache false;

**Comment by agrignard** [comment]
ok je test ca , le truc très chiant c'est que ca arrive au bout du'n certains moment donc aps evident à tracker..;  ca fait quoi en gros use_cache que je comprenne quand meme ce que j'ecris?

**Comment by ptaillandier** [comment]
Mettre use_cache à false permet de ne pas conserver en mémoire les plus
court chemin. Je ne sais pas pourquoi cela provoquerait une fuite mémoire,
mais c'est ce que j'ai vu quand j'ai testé avec le profiler. J'ai testé
jusqu'à 25000 pas de temp avec use_cache à false pour tous les graphes et
cela avait l'air de bien fonctionner sans fuite mémoire

Le ven. 24 janv. 2020 à 16:30, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
Ok la bonen news c'est que tu as un profiler (faudrait que tu m'apprennes ;-)  Tu utilises YourKit?

Je test ca rapidement

**Comment by ptaillandier** [comment]
Yep mais la version de 2016, pour lequel on a une licence GAMA.


Le ven. 24 janv. 2020 à 16:46, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
est ce que use_Cache false aussi pour celui la?
graph g <- as_edge_graph(lines); dans manage_cycle_network

**Comment by ptaillandier** [comment]
Oui tous

Le ven. 24 janv. 2020 à 16:49, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by ptaillandier** [comment]
En fait, celui là on s'en fiche

**Comment by agrignard** [comment]
ok je viens d'updater et je lance sur un ordi en // pour voir comment ça monte en memoire

**Comment by agrignard** [comment]
en fait j'avais fait tourner sur un autre ordi qui avait dans les preferences d'emmetre un warning, je close pour le moment l'issue
