### ISSUE TITLE
ca bouchonne dans paris...

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#58]
<img width="1830" alt="Screen Shot 2020-01-25 at 20 44 43" src="https://user-images.githubusercontent.com/3928502/73129503-93d30f00-3fb3-11ea-8241-d48012aa8a23.png">

**Comment by AlexisDrogoul** [comment]
Vu le nouveau projet, ça ne m'étonne pas trop 😄

**Comment by agrignard** [comment]
Ca bouchonne surtout maintenant en fait... après il n'y aura plus de voitures donc plus de bouchon comme par magie.

**Comment by ptaillandier** [comment]
Clairement, c'est une limite de ce projet qui est surtout une visualisation
et pas une étude de l'impact de ces changements : situation actuelle, il y
a plein de voitures; situation de demain avec leur nouvel aménagement :
comme par magie, les gens décident de ne plus utiliser leur voiture, mais
de plutôt se déplacer à pied ou à vélo :) .

Le mar. 28 janv. 2020 à 10:23, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
Bon enfin on s écarte du problème la. On peut avoir beaucoup de voiture et des embouteillages réaliste. Ce n'est pas parce qu il y a trop ou pas assez de voiture. De façon indépendante du projet il y a clairmenr des problems de bouchons sur un point de vue technique, le bug d'hier par exemple avec des paths pas cohérents, des voitures bloquées dans des culs de sac et des feux pas réalistes. Je  aid faire des issues plus spécifique pour isoler les problemes

**Comment by tnguyenh** [comment]
Pour l'instant le temps des feux est en cycles et pas en durée. Donc avec les simulations qui accélèrent ça fait des gros bouchons avec des feux qui restent rouges très longtemps.

Question: comment gérer les feux lorsque leur durée est inférieure à celle d'un cycle ?

**Comment by ptaillandier** [comment]
tu les desactives ?

Le mar. 28 janv. 2020 à 15:21, Tri Nguyen-Huu <notifications@github.com> a
écrit :

**Comment by tnguyenh** [comment]
Oui ça peut le faire. Je teste ça tout à l'heure.

**Comment by agrignard** [comment]
du coup on desactiverait les feux au monment du swicth pas bête!! Comem ca les voitures sont placés au bon endroit, y'a une variable globale pour tester ça?

**Comment by tnguyenh** [comment]
Ca bouchonne pour de vrai.
