### ISSUE TITLE
reduire le vert sur les chamsp before

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#61]
Pour accentuer le contraste reduire les espaces verts sur les champs before

**Comment by agrignard** [comment]
j'ai fait un noiveau shapefile mais ca foire, les park ne sont plus lu avec ce shapefile...

PCA_CE_EXP_EXI_NATURE_NEW.shp

**Comment by agrignard** [comment]
Normalemtn je comptais avoir juste un shape_file before et un after mais ca ne marche pas

**Comment by AlexisDrogoul** [comment]
A première vue, les espaces verts "before" ont l'air correct, pourtant ?

**Comment by agrignard** [comment]
l'idée était de contrasté un peu plsu avec le proposal mais je close cette issue pour le moment
