### ISSUE TITLE
Stroll_in_City Pietons en plein milieu des Champs Elysées

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#67]
Il y a des petits malins qui wanderent en plein milieu du rond point des champs Elysées, un peu d'ordre s'il vous plait, les selfies au milieu de la voie publique sont interdits!

<img width="688" alt="Screen Shot 2020-01-28 at 22 52 56" src="https://user-images.githubusercontent.com/3928502/73308666-16acd180-4221-11ea-9cdc-bedb7d9e702e.png">

**Comment by tnguyenh** [comment]
Ce sont les pedestrian qui sont dans l'état stroll_in_city qui ne suivent pas le graphe. @ptaillandier , une idée ? Je sèche là...

**Comment by tnguyenh** [comment]
Dans la dernière version que j'ai pushée, les piétons qui strollent dans la ville apparaissent en carrés verts. (on on supprimera ça bien entendu une fois le pb résolu).

**Comment by agrignard** [comment]
``````
	state stroll_in_city {
		float t <- machine_time;
		enter {
						test_ped <- true;
			stroll_time <- rnd(1, 10) *60;
			stroling_in_city<-true;
		}
		stroll_time <- stroll_time - 1;
		do wander amplitude:10.0 speed:2.0#km/#h;
		do updatefuzzTrajectory;
		transition to: walk_to_objective when: stroll_time = 0;
		exit{
			test_ped <- false;
			stroling_in_city<-false;
		}
		tmps_state[state] <- tmps_state[state] + (machine_time - t);
	}
`````

Ils font un wande peut-être pendant trop longtemps?


``````
stroll_time <- rnd(1, 10) *60;
``````

**Comment by tnguyenh** [comment]
Bon alors j'ai raconté n'importe quoi, il n'y a pas de bug avec le wander... Je m'occupe d'améliorer le comportement des piétons.

**Comment by tnguyenh** [comment]
@ptaillandier : on a un pb avec le wander. En fait, lorsque les pedestrians ont fait un goto sur le graphe, on se retrouve avec une nil value detected lorsqu'on lui demande plus tard de faire un wander sur ce même graphe. Est-ce que tu peux jeter un coup d'oeil au code (c'est sur le commit "no wanderers") ? On peut toujours faire un workaround, mais ce sera plus sale.

J'ai essayé de mettre tous les attributs utilisés dans le goto à nil, mais ça ne fonctionne pas. Dans le modèle, j'ai mis proba_wandering à 0 pour que le modèle continue de tourner sans planter, il faut donc remettre cette valeur à autre chose.

**Comment by ptaillandier** [comment]
c'est corrigé, vous pouvez mettre la proba que vous voulez

**Comment by tnguyenh** [comment]
ok merci

**Comment by agrignard** [comment]
ce bug est (à priori?) réglé

**Comment by tnguyenh** [comment]
Par contre les piétons sont à nouveau au milieu des champs.

**Comment by tnguyenh** [comment]
Les usages semblent mal placés, ils font aussi du shopping en plein milieu des voitures.

**Comment by agrignard** [comment]
a peut etre j'ai fait ca un peu à la va vite hier en ajoutant des fake usages... peut etre en effet les bouger... du coup ne pas oublier de mofidier dans les 2 GIS (avant et après) PCA_CE_EXP_EXI_USAGE et PCA_CE_EXP_PRO_USAGE

les fakes usage sont les cercle il faut leur donner un visibilité = "no"

**Comment by agrignard** [comment]
en effet y'a des restos en plein  milieu de la route! je m'occuep de bouger tout ça
<img width="1015" alt="Screen Shot 2020-02-08 at 19 04 19" src="https://user-images.githubusercontent.com/3928502/74089852-d877a380-4aa5-11ea-9c22-cdfecf81a8d7.png">
