### ISSUE TITLE
Les voitures sont sur les espaces verts dans le futur

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#69]
Il y a aura peut être que des 4x4 dans le futur mais c'est pas une raison pour rouler sur les espaces verts!

A priori juste ajusté l'offset en fucntion du nombre de line et de l'epaisseur de la voiture. Ca passe bien dans le présent
<img width="896" alt="Screen Shot 2020-01-28 at 23 18 23" src="https://user-images.githubusercontent.com/3928502/73310459-ad2ec200-4224-11ea-898d-69308f512c29.png">

**Comment by tnguyenh** [comment]
Presque réglé. C'est bon côté code, après il faudra ajuster le shapefile (lignes pas parfaitement parallèles) et la largeur des voies parce que ça tient juste juste.

**Comment by agrignard** [comment]
ça me parait good maintenant
