### ISSUE TITLE
better light trail

### ISSUE THREAD

**Issue by tnguyenh** [agrignard/ReChamp#73]
J'ai commité la nouvelle forme de traînées. Il y a encore des choses à discuter dessus: c'est mieux lorsque le step est grand, et moins bien quand le step est petit. Mais ce sera pas très dur de switcher de l'un à l'autre en fonction de la valeur du step.

Au passage @ptaillandier j'ai un peu galéré pour merger mes changements avec les tiens, j'espère ne pas avoir cassé les bouts de codes de ton benchmark (normalement non mais on sait jamais).

**Comment by agrignard** [comment]
On va dire qu'on est ok la dessus ( a verifier à l'usage entre les deux modes)
