### ISSUE TITLE
Spread more homogeneous bike

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#75]
<img width="1794" alt="Screen Shot 2020-02-01 at 02 34 15" src="https://user-images.githubusercontent.com/3928502/73584803-6696cd00-449b-11ea-9c7a-cfc3e16d82b1.png">

**Comment by agrignard** [comment]
@ptaillandier tu penses pouvoir y jter un oeil? Le graph a été reconnecté à partir des pistes cyclables, mais je suis surpris qu'il en passe pas assez par les champs

**Comment by ptaillandier** [comment]
euh, faut faire quoi ?

**Comment by agrignard** [comment]
Les forcer à pendre plus les champs. Peut être se servir de origin destination qu on a utilisé pour les car

**Comment by agrignard** [comment]
du coup meme avec le proba_hot_target il ya tjs beaucup trop de velo pas sur les champs
<img width="1394" alt="Screen Shot 2020-02-04 at 23 44 47" src="https://user-images.githubusercontent.com/3928502/73794335-7f0f2c00-47a8-11ea-9689-8d47f0e9b1b5.png">

**Comment by agrignard** [comment]
je le colse car dupliqué avec un autre
