### ISSUE TITLE
Desynchronisation des feux lors des changements de scenarios

### ISSUE THREAD

**Issue by tnguyenh** [agrignard/ReChamp#78]
![image](https://user-images.githubusercontent.com/18676913/73707628-6fd2a480-46fc-11ea-9913-4b37c0544a58.png)

Feux à resynchroniser lorsque certains se désactivent et se réactivent.

**Comment by agrignard** [comment]
@tnguyenh c'est réglé ç aou pas????

**Comment by agrignard** [comment]
@tnguyenh on est ok la dessus non? Je te laisse fermer si c est good

**Comment by tnguyenh** [comment]
fixed.
