### ISSUE TITLE
Issue with wander

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#79]
voir ce commit
https://github.com/agrignard/ReChamp/commit/5382cab65b6819233a8949f418c267b4cda8ea9e

ca foire quand on change de mode (je remet la proba a 0 pour le moment)

``````
2 occurrences in 2 agents at cycle 202: Java error: nil value detected
in 
NullPointerException: null
in agents pedestrian487, Simulation 0
``````

**Comment by agrignard** [comment]
pour le moment
`````
float proba_wandering <- 0;
`````

mais on doit pouvori mettre une valeur

**Comment by tnguyenh** [comment]
Je regarde demain, ça vient peut-être d'autre chose.

**Comment by ptaillandier** [comment]
C'est normalement corrigé (c'était parce que le graphe piéton était
modifié, mais qu'ils avaient toujours des infos en cache sur l'ancien
graphe, d'où des bugs qui apparaissaient).

Le mer. 5 févr. 2020 à 01:12, Tri Nguyen-Huu <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
Ok à tester pusher et je fermerai l'issue
