### ISSUE TITLE
Remplir entre le petit et grand palais après

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#83]
Mettre plus de pietons voir des zones piétonnes

**Comment by tnguyenh** [comment]
Plusieurs solutions: agrandir le trottoir de la rue comme pour les Champs, mais ça ramène moins de monde. Où rajouter des usages invisibles, et des parcs (en particulier les Invalides ?). La dernière solution permet de rajouter des flux de piétons y compris sur le pont.

**Comment by agrignard** [comment]
ca me parait beaucoup mieux avec les usages invisibles pour le moment

A voir au cas par cas in situ
