### ISSUE TITLE
don't show peope when inside usage

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#84]
Request from the curattor (super easy to do)

**Comment by agrignard** [comment]
pas si easy que ca en fait , si on ren dinvisble les gens dans les usages on les voit pas sur concorde après... j'annule cette request pour le moment, je vois pas trop ou est le probleme de voir les gens dans le grand palais en fait

**Comment by tnguyenh** [comment]
Je suis d'accord avec le curateur, je préfère ne pas les voir dans les bâtiments. Du coup j'ai implémenté ce truc, on peut rajouter un peu de piétons agents du coup. C'est facilement enlevable si ça ne te plaît pas.
