### ISSUE TITLE
Compilation error with the new version  of GAMA

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#94]
I just downloaded the continousbuild of GAMA and the OSML Loading Drving doesn't compile anymore
````
save road type:"shp" to:"../includes/roads_OSM.shp" with:[lanes::"lanes",maxspeed::"maxspeed", oneway::"oneway"] ;
save intersection type:"shp" to:"../includes/nodes_OSM.shp" with:[type::"type", crossing::"crossing"] ;
````

**Comment by AlexisDrogoul** [comment]
Create a fresh workspace or copy the erroneous models from a fresh workspace to your old one. These models have all been corrected.
